version: '3.0'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes: 
      - mysql-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=apps
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todo
      - MYSQL_RANDOM_ROOT_PASSWORD=true
  todo:
    build: .
    depends_on:
      - mysql
    ports:
      - "8888:8888"
    restart: always
    
volumes:
  mysql-db:
